### PR TITLE
CustomizerDefault.options ElementAdder_Tier for Endgame utility + life&mana flasks

### PR DESCRIPTION
**Pull request by cdrg**
Split "other" section in two to support ElementAdder_Tier for both Utility and Life&Mana. General standardization & cleanup.

### CODE REVIEW

**Comment by Tobnac** [comment]
As per ReadMe:
FILTER-QUERY-ID: Unique name that identifies this query. Will be sometimes referred as 'filter-rule-name' Having the same name for different rules is not allowed. **Changing the ID of a rule after initial release is also not recommended**. This value is used for the save&load system and therefore very critical.

Even simple changes like "High Level Life/Mana Flasks - iLvl 82" -> "High Level Life & Mana Flasks - iLvl 82" are enough to cause problems here. Because this string is the main method to find the right filter rule to edit for the saveLoad system. Meaning if you change this name here, all existing changes to these rules will be invalidated. You will have to use the Title parameter to change displayNames here:
https://github.com/NeverSinkDev/FilterBlade-Public-Assets/blob/main/README_OptionFile.md#-title

I'll update the ReadMe with this info.

Then in line 1305 you wrote $sdh instead of $shd.
While the actual order of the "SHD" string value does not matter, $shd here is a variable, meaning you need to be exact when accessing this variable.

If you're feeling fancy you can also add some default appearance lines to the base conditional rule. Such as size or color. But since those are just simple flasks, we can live without any here.

Otherwise a very solid first attempt at working with option files :P

**Comment by cdrg** [comment]
Updated with fixes to the above.

I couldn't think of any default styling for flasks that would add value.

**Comment by Tobnac** [comment]
Nice!
The other function also has the $shd typo, and @NeverSinkDev do we need rarity and arealevel filtering by default in these new custom rules? I think it's gonna catch uniques and maybe leveling if we dont, right?

**Comment by cdrg** [comment]
Doh. Fixed the typo and add default Rarity Normal Magic. None of the other flask rules have AreaLevel set, is that just for custom rules?

**Comment by NeverSinkDev** [comment]
Looks good to me, thanks!

**Pull request merged**
